### ISSUE TITLE
Example data as plain text

### ISSUE THREAD

**Issue by johanneskoester** [ZhuangLab/MERFISH_analysis#1]
Dear MERFISH team,  
would it be possible to provide the new example data as plain text/csv or excel files, in a format similar to the MHD4 and MHD2 data provided together with the original paper?

Best,
Johannes

**Comment by johanneskoester** [comment]
Or is the provided data (http://zhuang.harvard.edu/merfish/MERFISHData/MERFISH_Examples.zip) the same as this one: http://zhuang.harvard.edu/merfish/MERFISHData/140genesData.xlsx and http://zhuang.harvard.edu/merfish/MERFISHData/1001genesData.xlsx, only in a different format plus raw data?
If so, can we expect the data from the new publication soon?

**Comment by ZhuangLab** [comment]
Hi Johannes,

Yes the new data are coming. We have adopted a binary format for these data, given their substantial increase in size. We should have example tools for loading this files posted as well.

**Comment by johanneskoester** [comment]
Wait, will I be able to load the binary format without Matlab?  Matlab is closed source and not available to everybody. E.g. you could use [HDF5](https://support.hdfgroup.org/HDF5/) from Cern, which is the de-facto standard for encoding arbitrary binary data nowadays. There are HDF5 readers and writers available for any major programming language.
It is also supported directly from within Matlab.

Sorry to bug you with this, but I am the dev of the [MERFISHtools](http://merfishtools.github.io/) package. It would be great if MERFISH as a technology would support interoperable, free file exchange standards right from the start. Please let me know if I can help with this.
